# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be84dd9ee94c15c1231cf26293232bde"
application_url = "https://recently-dance-housing-offering.trycloudflare.com"
embedded = true
name = "boa-home-task-SJ"
handle = "boa-home-task-sj"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-225.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://recently-dance-housing-offering.trycloudflare.com/auth/callback",
  "https://recently-dance-housing-offering.trycloudflare.com/auth/shopify/callback",
  "https://recently-dance-housing-offering.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
